<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_A work email is recommended to access _330bd4</name>
   <tag></tag>
   <elementGuidId>bfa3ece8-37d8-4116-aede-4546fad97e5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@action='/realms/katalon/login-actions/authenticate?session_code=RqmNxZJLD9I0Na4iY1G6DMbjaORToNb0jo0GUIjfJ18&amp;execution=f5fd9481-61f4-4ff1-94ce-2bfbc301145c&amp;client_id=katalon-marketing&amp;tab_id=LL0pyYeOIus']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>form.form_sign_up</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>form >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>8cd953a5-0e98-4765-a96b-ea24b51867b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form_sign_up</value>
      <webElementGuid>e19d6e36-2ce6-4b8b-a8ff-936d2dbe53e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onsubmit</name>
      <type>Main</type>
      <value>login.disabled = true; return true;</value>
      <webElementGuid>072b84ae-3b2b-4b81-aee1-786ffe1aaf1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>action</name>
      <type>Main</type>
      <value>/realms/katalon/login-actions/authenticate?session_code=RqmNxZJLD9I0Na4iY1G6DMbjaORToNb0jo0GUIjfJ18&amp;execution=f5fd9481-61f4-4ff1-94ce-2bfbc301145c&amp;client_id=katalon-marketing&amp;tab_id=LL0pyYeOIus</value>
      <webElementGuid>62cd5017-edcb-422c-a107-82cbbda60937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>method</name>
      <type>Main</type>
      <value>POST</value>
      <webElementGuid>7b3dac49-e23c-4ab4-b7f4-cb294e06a82e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-form-interact-id</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dc961bbb-665e-4f4f-9ad8-31f6e25ff8ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kc-content-wrapper&quot;)/div[@class=&quot;wrapSignIn login_screen show_recommended_message&quot;]/div[@class=&quot;main_content&quot;]/div[@class=&quot;left_content&quot;]/div[@class=&quot;top_section&quot;]/div[@class=&quot;form_section&quot;]/div[@class=&quot;signin_method_section signin_email_section active&quot;]/form[@class=&quot;form_sign_up&quot;]</value>
      <webElementGuid>33ac80e5-125f-470a-9eae-b34912fc25bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@action='/realms/katalon/login-actions/authenticate?session_code=RqmNxZJLD9I0Na4iY1G6DMbjaORToNb0jo0GUIjfJ18&amp;execution=f5fd9481-61f4-4ff1-94ce-2bfbc301145c&amp;client_id=katalon-marketing&amp;tab_id=LL0pyYeOIus']</value>
      <webElementGuid>c475db43-6301-4f2d-813e-fcd57d73a694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kc-content-wrapper']/div/div[2]/div/div/div[2]/div[2]/form</value>
      <webElementGuid>c7fb5a40-0a38-490a-923a-a8d97c258167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A work email is recommended to access Studio Enterprise 30-day trial.'])[2]/following::form[1]</value>
      <webElementGuid>eafd1e88-4c7a-4512-bdcd-ffb37235e61e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in with email'])[1]/following::form[1]</value>
      <webElementGuid>5227b86a-1147-44cf-b7fa-07cc8fe37c74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Katalon domain'])[1]/preceding::form[1]</value>
      <webElementGuid>56eeba10-2131-44ee-9fb8-1a1c39747718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='katalon.io'])[1]/preceding::form[1]</value>
      <webElementGuid>7838442b-5c6e-45bc-b77d-92c2ec7a619b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>768fb5cb-87e9-4b86-93c5-afc026c7193a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
